id: P009606
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:40:26.019487
source_metadata:
  id: bdr:W23844
  title: གསང་འདུས་རྒྱུད་འགྲེལ་ལེ་དང་ཡན་གྱི་གསལ་སྒྲོན
  author: ''
  volumes:
    3b7ff9be87de4d6085ba0f69e676b36d:
      image_group_id: I3015
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
